// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoZy7nrNb2-dnqSj3WenxaNSuDLO2mpvs',
    appId: '1:195252538925:web:f9a0654a94701eda2df2a4',
    messagingSenderId: '195252538925',
    projectId: 'safe-internet-hero',
    authDomain: 'safe-internet-hero.firebaseapp.com',
    storageBucket: 'safe-internet-hero.firebasestorage.app',
    measurementId: 'G-2L7EL9HM1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDehb-HZw9xkjFWWQ-uDG8nH-GVqIzJcGM',
    appId: '1:195252538925:android:76d6e05892002b162df2a4',
    messagingSenderId: '195252538925',
    projectId: 'safe-internet-hero',
    storageBucket: 'safe-internet-hero.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0PV4jzjhzDe9i-UAbfWSYZseckJjnvXU',
    appId: '1:195252538925:ios:5392c461f0d464692df2a4',
    messagingSenderId: '195252538925',
    projectId: 'safe-internet-hero',
    storageBucket: 'safe-internet-hero.firebasestorage.app',
    iosBundleId: 'com.example.safeInternetHero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0PV4jzjhzDe9i-UAbfWSYZseckJjnvXU',
    appId: '1:195252538925:ios:5392c461f0d464692df2a4',
    messagingSenderId: '195252538925',
    projectId: 'safe-internet-hero',
    storageBucket: 'safe-internet-hero.firebasestorage.app',
    iosBundleId: 'com.example.safeInternetHero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM__yw9abaXOlFBPUj1IMskR0eQU1O2ww',
    appId: '1:195252538925:web:e962972ad40821f42df2a4',
    messagingSenderId: '195252538925',
    projectId: 'safe-internet-hero',
    authDomain: 'safe-internet-hero.firebaseapp.com',
    storageBucket: 'safe-internet-hero.firebasestorage.app',
    measurementId: 'G-4HC3GY2TVE',
  );
}
